backend:
  name: git-gateway
  branch: main

# It is safer to point these to a specific folder
media_folder: "public" 
public_folder: ""     

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/index.astro"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Description", name: "description", widget: "string" }
          - { label: "Hero Main Heading", name: "hero_title", widget: "string" }
          - { label: "Hero Subtext", name: "hero_subtext", widget: "text" }